[project]
name = "yolo-training-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12.2, <3.13"
dependencies = [
    "pyqt6>=6.8.1",
    "pyqt6-qt6>=6.8.2",
    "pyqt6-sip>=13.10.0",
    "ultralytics==8.3.78",
    "albumentations>=2.0.5",
    "opencv-python>=4.8.0",
    "psutil>=5.9.0",
    "numpy<=2.1.1",
    "pillow>=10.2.0",
    "requests>=2.31.0"
]

[tool.uv.pip]
index-url = "https://download.pytorch.org/whl/cu126"

[tool.setuptools]
packages = ["create", "demo_model", "gui", "nxt_camera", "remove", "utils", "yolo"]



