[project]
name = "yolo-training-app"
version = "0.1.0"
requires-python = ">=3.11,<3.12"

dependencies = [
    "ultralytics>=8.3.85",
    "pyqt6>=6.5.2",
    "ultralytics>=8.3.85",
    "pyqt6>=6.5.2",
    "opencv-python>=4.8.0",
    "psutil>=5.9.0",
    "numpy<=2.1.1",
    "pillow>=10.2.0",
    "requests>=2.31.0",
    "optuna>=4.2.1",
    "albumentations",
    "emoji>=2.14.1",
]

[tool.uv.pip]
index-strategy = "unsafe-best-match"
index-url = "https://download.pytorch.org/whl/cu126"
extra-index-url = ["https://pypi.org/simple"]

[tool.setuptools]
packages = ["gui", "yolo", "nxt_camera", "utils"]

